### ISSUE TITLE
Test failures if LinguaPlone is not installed

### ISSUE THREAD

**Issue by tomgross** [Jarn/collective.solr#1]
Some tests of collective.solr fail, if LinguaPlone is not installed.
The solution is either to 

a) specify it as a dependency or 
b) don't run these tests, if LP is not available.

**Comment by hannosch** [comment]
c) Mark it as a test dependency, like we already do:

```
extras_require = { 'test': [
  'cElementTree',
  'collective.testcaselayer',
  'Products.LinguaPlone >=3.1a1',
  'Products.PloneTestCase',
  'zope.testing',
]},
```

**Comment by witsch** [comment]
earlier on i tried to have the tests work with and without linguaplone, but that can become very cumbersome.  so if it's only about slight differences in markup — which was the case several times before — i agree that it's probably better to make LP a test dependency indeed.

**Comment by hannosch** [comment]
The current way of marking it as a test dependency seems to be good enough.
