### ISSUE TITLE
exception when searching in Plone

### ISSUE THREAD

**Issue by domruf** [Jarn/collective.solr#3]
I installed collective.solr in my plone test site but I get the following exception when I search something

...
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
  Module zope.tales.tales, line 696, in evaluate
- URL: file:/usr/local/Plone/buildout-cache/eggs/Plone-4.0.7-py2.6.egg/Products/CMFPlone/skins/plone_forms/search.pt
- Line 146, Column 12
- Expression: <PathExpr standard:u'result/getURL'>
- Names:
    {'container': <PloneSite at /Plone>,
     'context': <PloneSite at /Plone>,
     'default': <object object at 0xb77006e0>,
     'here': <PloneSite at /Plone>,
     'loop': {u'result': <Products.PageTemplates.Expressions.PathIterator object at 0xfc6e9ac>},
     'nothing': None,
     'options': {'args': ()},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xfcfb964>,
     'request': <HTTPRequest, URL=http://10.4.177.158:8080/Plone/search>,
     'root': <Application at >,
     'template': <FSPageTemplate at /Plone/search>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>}
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 157, in _eval
  Module Products.PageTemplates.Expressions, line 119, in render
  Module collective.solr.flare, line 52, in getURL
  Module collective.solr.flare, line 34, in getPath
  KeyError: 'physicalPath'

**Comment by hannosch** [comment]
You have a mismatch between your Solr schema and the collective.solr code. Please use the Solr schema from https://github.com/Jarn/collective.solr/blob/2.0/buildout/solr.cfg for collective.solr 2.0.

The current master (what will become 3.0) changes the way the "path" index is emulated and requires a schema change.

I'll fix the installation instructions as shown on PyPi to refer to the correct schema for each version.

**Comment by domruf** [comment]
yep now it works
that was really quick thanks
